<wsdl:definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/SD_PaymentPanel_App/SD_SettledTrxDetails/dbReference" name="dbReference-concrete" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:import location="dbReference.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/SD_PaymentPanel_App/SD_SettledTrxDetails/dbReference"/>
    <wsdl:binding name="dbReference_ptt-binding" type="dbr:dbReference_ptt" xmlns:dbr="http://xmlns.oracle.com/pcbpel/adapter/db/SD_PaymentPanel_App/SD_SettledTrxDetails/dbReference">
        <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
        <wsdl:operation name="dbReference">
            <soap:operation soapAction="dbReference"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>