<wsdl:definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/SD_PaymentPanel_App/SD_PaymentTermDetails/SD_PaymentTermDetails_PR_businessService" name="SD_PaymentTermDetails_PR_businessService-concrete" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:import location="SD_PaymentTermDetails_PR_businessService.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/SD_PaymentPanel_App/SD_PaymentTermDetails/SD_PaymentTermDetails_PR_businessService"/>
    <wsdl:binding name="SD_PaymentTermDetails_PR_businessService_ptt-binding" type="sd:SD_PaymentTermDetails_PR_businessService_ptt" xmlns:sd="http://xmlns.oracle.com/pcbpel/adapter/db/SD_PaymentPanel_App/SD_PaymentTermDetails/SD_PaymentTermDetails_PR_businessService">
        <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
        <wsdl:operation name="SD_PaymentTermDetails_PR_businessService">
            <soap:operation soapAction="SD_PaymentTermDetails_PR_businessService"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>