<wsdl:definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/SD_PaymentPanel_App/SD_SettledTrxViewmore/SD_SettledTrxViewmore_BusinesService" name="SD_SettledTrxViewmore_BusinesService-concrete" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:import location="SD_SettledTrxViewmore_BusinesService.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/SD_PaymentPanel_App/SD_SettledTrxViewmore/SD_SettledTrxViewmore_BusinesService"/>
    <wsdl:binding name="SD_SettledTrxViewmore_BusinesService_ptt-binding" type="sd:SD_SettledTrxViewmore_BusinesService_ptt" xmlns:sd="http://xmlns.oracle.com/pcbpel/adapter/db/SD_PaymentPanel_App/SD_SettledTrxViewmore/SD_SettledTrxViewmore_BusinesService">
        <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
        <wsdl:operation name="SD_SettledTrxViewmore_BusinesService">
            <soap:operation soapAction="SD_SettledTrxViewmore_BusinesService"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>