<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java"
                xmlns:ns0="http://xmlns.oracle.com/pcbpel/adapter/db/Get_SD_UnsettledTrx_BusinessService"
                xmlns:DVMFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.dvm.DVMFunctions"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:BasicCredentialsUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.BasicCredentialsUserFunction"
                xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas"
                xmlns:UUIDUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.UUIDUserFunction"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:tns="http://www.unsettledTrx.org"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:IsUserInRoleFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInRoleFunction"
                xmlns:IsUserInGroupFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInGroupFunction"
                xmlns:XrefFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.xref.XrefFunctions"
                exclude-result-prefixes="xsi oracle-xsl-mapper xsl xsd ns0 tns oraxsl DVMFunctions BasicCredentialsUserFunction UUIDUserFunction IsUserInRoleFunction IsUserInGroupFunction XrefFunctions">
  <oracle-xsl-mapper:schema>
    <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
    <oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:source type="XSD">
        <oracle-xsl-mapper:schema location="../Resources/Get_SD_UnsettledTrx_BusinessService.xsd"/>
        <oracle-xsl-mapper:rootElement name="Get_SD_UnsettledTrx_BusinessServiceOutputCollection"
                                       namespace="http://xmlns.oracle.com/pcbpel/adapter/db/Get_SD_UnsettledTrx_BusinessService"/>
      </oracle-xsl-mapper:source>
    </oracle-xsl-mapper:mapSources>
    <oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:target type="XSD">
        <oracle-xsl-mapper:schema location="../Schema/SD_unsettledTrx.xsd"/>
        <oracle-xsl-mapper:rootElement name="UnsettledTrxOutput" namespace="http://www.unsettledTrx.org"/>
      </oracle-xsl-mapper:target>
    </oracle-xsl-mapper:mapTargets>
    <!--GENERATED BY ORACLE XSL MAPPER 12.1.3.0.0(XSLT Build 140529.0700.0211) AT [FRI JUN 05 12:42:22 IST 2015].-->
  </oracle-xsl-mapper:schema>
  <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
  <xsl:template match="/">
    <tns:UnsettledTrxOutput>
      <xsl:for-each select="/ns0:Get_SD_UnsettledTrx_BusinessServiceOutputCollection/ns0:Get_SD_UnsettledTrx_BusinessServiceOutput">
        <tns:UnsettledTrxComplexCollection>
          <tns:transactionDate>
            <xsl:value-of select="ns0:transactiondate"/>
          </tns:transactionDate>
          <tns:suborderTxnId>
            <xsl:value-of select="ns0:suborderTxnId"/>
          </tns:suborderTxnId>
          <tns:transactionType>
            <xsl:value-of select="ns0:transactionType"/>
          </tns:transactionType>
          <tns:transactionReason>
            <xsl:value-of select="ns0:transactionReason"/>
          </tns:transactionReason>
          <tns:sellerCode>
            <xsl:value-of select="ns0:sellerCode"/>
          </tns:sellerCode>
          <tns:productName>
            <xsl:value-of select="ns0:productName"/>
          </tns:productName>
          <tns:sellerSku>
            <xsl:value-of select="ns0:sellerSku"/>
          </tns:sellerSku>
          <tns:webSalePrice>
            <xsl:value-of select="string (ns0:webSalePrice )"/>
          </tns:webSalePrice>
          <tns:onHold>
            <xsl:value-of select="ns0:onHold"/>
          </tns:onHold>
          <tns:dueAmount>
            <xsl:value-of select="string (ns0:dueAmount )"/>
          </tns:dueAmount>
          <tns:dueDate>
            <xsl:value-of select="ns0:dueDate"/>
          </tns:dueDate>
          <tns:action>
            <xsl:value-of select="ns0:action"/>
          </tns:action>
          <tns:created>
            <xsl:value-of select="ns0:created"/>
          </tns:created>
          <tns:updated>
            <xsl:value-of select="ns0:UPDATED"/>
          </tns:updated>
        </tns:UnsettledTrxComplexCollection>
      </xsl:for-each>
    </tns:UnsettledTrxOutput>
  </xsl:template>
</xsl:stylesheet>
